app/front/models/Aytam.php
<?php

namespace front\models;

use Yii;
use dektrium\user\models\User;

/**
 * This is the model class for table "Aytam".
 *
 * @property int $id
 * @property string $emridokumentit
 * @property double $nrjetimit
 * @property int $user_id
 * @property int $iddonator
 * @property double $nrdonatorit
 * @property string $linkufotografise
 * @property string $linkuraportitvideo
 * @property string $linkuraportittekst
 *
 * @property User $user
 */
class Aytam extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'Aytam';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id', 'user_id'], 'required'],
            [['id', 'user_id', 'iddonator'], 'integer'],
            [['nrjetimit', 'nrdonatorit'], 'number'],
            [['emridokumentit', 'linkufotografise', 'linkuraportitvideo', 'linkuraportittekst'], 'string', 'max' => 255],
            [['id'], 'unique'],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'emridokumentit' => Yii::t('app', 'Emridokumentit'),
            'nrjetimit' => Yii::t('app', 'Nrjetimit'),
            'user_id' => Yii::t('app', 'User ID'),
            'iddonator' => Yii::t('app', 'Iddonator'),
            'nrdonatorit' => Yii::t('app', 'Nrdonatorit'),
            'linkufotografise' => Yii::t('app', 'Linkufotografise'),
            'linkuraportitvideo' => Yii::t('app', 'Linkuraportitvideo'),
            'linkuraportittekst' => Yii::t('app', 'Linkuraportittekst'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    /**
     * {@inheritdoc}
     * @return AytamQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new AytamQuery(get_called_class());
    }
}

app/front/controllers/AytamController.php
<?php

namespace front\controllers;

use Yii;
use front\models\Aytam;
use front\models\AytamSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use dektrium\user\filters\AccessRule;


/**
 * AytamController implements the CRUD actions for Aytam model.
 */
class AytamController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
			    'class' => AccessControl::className(),
			    'ruleConfig' => [
			        'class' => AccessRule::className(),
			    ],
			    'rules' => [
			        [
			            'actions' => ['create'],
			            'allow' => true,
			            'roles' => ['admin'],
			        ],
			        [
			            'actions' => ['index','view','search'],
			            'allow' => true,
			            'roles' => ['@', 'admin'],
			        ],
			    ],
			],
        ];
    }

    /**
     * Lists all Aytam models.
     * @return mixed
     */
    public function actionIndex()
    {
        
        //echo 'User is not logged!';
        $searchModel = new AytamSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
       
    }

    /**
     * Displays a single Aytam model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel(['user_id' => Yii::$app->user->getID()]),
        ]);
    }

    /**
     * Creates a new Aytam model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Aytam();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Aytam model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Aytam model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Aytam model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Aytam the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Aytam::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

app/front/views/aytam/_aytam.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

$photoInfo = $model->nrjetimit;
$photo = Html::img($photoInfo['url'],['alt'=>$photoInfo['alt']]);
$detailLink = Url::toRoute(['/aytam/view','id'=>$model->id]);
?>

<figure>
    <?=Html::a($photo,$detailLink,['class'=>'profile-thumb'])?>
</figure>

<ul class="details">
    <li class="btn btn-info"><span>Orphan Number:</span> <?=$model->nrjetimit?></li>
    <li><span>Image Link:</span> <?php echo Html::a('Image Link', $model->linkufotografise, ['target'=>'_blank']);?> </li>
    <li><span>Video report link:</span> <?php echo Html::a('Video Report Link', $model->linkuraportitvideo, ['target'=>'_blank']);?> </li>
    <li><span>Text report link:</span> <?php echo Html::a('Text Report Link', $model->linkuraportittekst, ['target'=>'_blank']);?> </li>
</ul>
<br>

app/front/views/aytam/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model front\models\Aytam */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="aytam-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'id')->textInput() ?>

    <?= $form->field($model, 'emridokumentit')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'nrjetimit')->textInput() ?>

    <?= $form->field($model, 'user_id')->textInput() ?>

    <?= $form->field($model, 'iddonator')->textInput() ?>

    <?= $form->field($model, 'nrdonatorit')->textInput() ?>

    <?= $form->field($model, 'linkufotografise')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'linkuraportitvideo')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'linkuraportittekst')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

app/front/views/aytam/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model front\models\AytamSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="aytam-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>


    <?= $form->field($model, 'nrjetimit') ?>

    <?php // echo $form->field($model, 'nrdonatorit') ?>

    <?php // echo $form->field($model, 'linkufotografise') ?>

    <?php // echo $form->field($model, 'linkuraportitvideo') ?>

    <?php // echo $form->field($model, 'linkuraportittekst') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

app/front/views/aytam/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model front\models\Aytam */

$this->title = Yii::t('app', 'Create Aytam');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Aytams'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="aytam-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

app/front/views/aytam/index.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel front\models\AytamSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Aytams');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="aytam-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php Pjax::begin(); ?>
    <?php echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= ListView::widget([
        'dataProvider' => $dataProvider,
        'itemView' => '_aytam',
        'itemOptions' => ['class'=>'list-aytam'],
        //'layout' => "{sorter}\n{summary}\n{items}\n{pager}"
        //'itemOptions' => ['class' => 'item'],
        //'itemView' => function ($model, $key, $index, $widget) {
        //    return Html::a(Html::encode($model->nrjetimit), ['view', 'id' => $model->id]);
       // },
    ]) ?>
    <?php Pjax::end(); ?>
</div>

app/front/views/aytam/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model front\models\Aytam */

$this->title = Yii::t('app', 'Update Aytam: ' . $model->id, [
    'nameAttribute' => '' . $model->id,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Aytams'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="aytam-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

app/front/views/aytam/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model front\models\Aytam */

$this->title = $model->nrjetimit;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Aytams'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="aytam-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            //'id',
            //'emridokumentit',
            'nrjetimit',
          
            //'iddonator',
            'nrdonatorit',
          
            //'linkufotografise:url',
            
            [
                'attribute' => 'linkufotografise',
                'label' => 'Image Link',
                'format' => 'raw',
                'value' => function ($model) {
                     //return \Yii::$app->formatter->asUrl($model->linkufotografise, ['target' => '_blank']);
                     //$doc = "<a href='$model->linkuraportitvideo'>linku raportit video</a>";
                     return Html::a('Click to open', $model->linkufotografise, ['target'=>'_blank']);
                     //return $doc;
                 },
            ],
			
			[
                'attribute' => 'linkufotografise',
                'label' => 'Video Report Link',
                'format' => 'raw',
                'value' => function ($model) {
                     //return \Yii::$app->formatter->asUrl($model->linkufotografise, ['target' => '_blank']);
                     //$doc = "<a href='$model->linkuraportitvideo'>linku raportit video</a>";
                     return Html::a('Click to open', $model->linkuraportitvideo, ['target'=>'_blank']);
                     //return $doc;
                 },
            ],
			[
                'attribute' => 'linkufotografise',
                'label' => 'Text Report Link',
                'format' => 'raw',
                'value' => function ($model) {
                     //return \Yii::$app->formatter->asUrl($model->linkufotografise, ['target' => '_blank']);
                     //$doc = "<a href='$model->linkuraportitvideo'>linku raportit video</a>";
                     return Html::a('Click to open', $model->linkuraportittekst, ['target'=>'_blank']);
                     //return $doc;
                 },
            ],

            //'linkuraportitvideo:url',
            //'linkuraportittekst:url',
            //'donator.nrtelefonit',
        ],
    ]) ?>

</div>