app/front/controllers/AytamController.php
<?php

namespace front\controllers;

use Yii;
use front\models\Aytam;
use front\models\AytamSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use dektrium\user\filters\AccessRule;


/**
 * AytamController implements the CRUD actions for Aytam model.
 */
class AytamController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
			    'class' => AccessControl::className(),
			    'ruleConfig' => [
			        'class' => AccessRule::className(),
			    ],
			    'rules' => [
			        [
			            'actions' => ['create'],
			            'allow' => true,
			            'roles' => ['admin'],
			        ],
			        [
			            'actions' => ['index','view','search'],
			            'allow' => true,
			            'roles' => ['@', 'admin'],
			        ],
			    ],
			],
        ];
    }

    /**
     * Lists all Aytam models.
     * @return mixed
     */
    public function actionIndex()
    {
        
        //echo 'User is not logged!';
        $searchModel = new AytamSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
       
    }

    /**
     * Displays a single Aytam model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel(['user_id' => Yii::$app->user->getID()]),
        ]);
    }

    /**
     * Creates a new Aytam model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Aytam();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Aytam model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Aytam model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Aytam model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Aytam the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Aytam::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

app/front/views/layouts/main.php
<?php

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use base\widgets\Alert;
use front\assets\AppAsset;
use base\widgets\LangSelect;

/**
 * @var $this    yii\web\View
 * @var $content string
 */
raoul2000\bootswatch\BootswatchAsset::$theme = 'readable';
//AppAsset::register($this);
$dir_ar = "dir='rtl'";
$dir_en = "dir='ltr'";
AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>"
<?php
    if(Yii::$app->language=='ar')
       echo $dir_ar;
    ?>
    >
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">

    <?php NavBar::begin([
        'brandLabel' => Yii::$app->params['brandLabel'],
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-default navbar-fixed-top',
        ],
    ]);

    $menuItems = [
        //['label' => Yii::t('app', 'Home'), 'url' => ['/site/index']],
    ];

    if (Yii::$app->user->isGuest) {
        //$menuItems[] = ['label' => Yii::t('app', 'Sign up'), 'url' => ['/user/registration/register']];
        //$menuItems[] = ['label' => Yii::t('app', 'رابط احياء التراث الإسلامي'), 'url' => ['http://turathkw.com/']];
        //$menuItems[] = ['label' => Yii::t('app', 'رابط احياء التراث الإسلامي'), 'url' => ['http://turathkw.com/','linkOptions' => ['target' => '_blank']]];
        $menuItems[] = ['label' => Yii::t('app', 'Sign in'), 'url' => ['/user/security/login']];
    } else {
        //$menuItems[] = ['label' => Yii::t('app', 'رابط احياء التراث الإسلامي'), 'url' => ['http://turathkw.com/']];
        $menuItems[] = ['label' => Yii::t('app', 'Aytam'), 'url' => ['/aytam/index']];
        $menuItems[] = ['label' => Yii::t('app', 'Profile'), 'url' => ['/user/settings/profile']];
        $menuItems[] = '<li>'
            . Html::beginForm(['/user/security/logout'], 'post')
            . Html::submitButton(Yii::t('app', 'Sign out') . ' ' . Yii::$app->user->identity->username, ['class' => 'btn btn-link'])
            . Html::endForm()
            . '</li>';
    }

    $menuItems[] = LangSelect::widget();

    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);

    NavBar::end(); ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer role="contentinfo">
    <div class="container">
        <p class="text-muted pull-left">&copy; <?= date('Y') . ' ' . Yii::$app->name; ?></p>
        <p class="text-muted pull-right"><?= Html::a('Instagram', 'https://www.instagram.com/turathkw/', ['class'=>'btn btn-block btn-social btn-instagram'],['target'=>'_blank']) ?></p>
		<p class="text-muted pull-right"><?= Html::a('Youtube', 'https://www.youtube.com/user/turathkwr/playlists?view_as=subscriber', ['class'=>'btn btn-block btn-social btn-youtube'],['target'=>'_blank']) ?></p>
		<p class="text-muted pull-right"><?= Html::a('Twitter', 'https://twitter.com/turathkw', ['class'=>'btn btn-block btn-social btn-twitter'],['target'=>'_blank']) ?></p>
		<p class="text-muted pull-right"><?= Html::a('Facebook', 'https://www.facebook.com/turathkuw/', ['class'=>'btn btn-block btn-social btn-facebook'],['target'=>'_blank']) ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>